# Generated by Django 5.0.3 on 2024-03-10 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rick_morty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rickmortymodel',
            name='especie',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Especie'),
        ),
        migrations.AddField(
            model_name='rickmortymodel',
            name='genero',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Gênero'),
        ),
        migrations.AddField(
            model_name='rickmortymodel',
            name='nome',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Nome do personagem'),
        ),
        migrations.AddField(
            model_name='rickmortymodel',
            name='origem',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Local de origem'),
        ),
    ]
